### ISSUE TITLE
Poetry dependency resolution fails. PyPi 1.0.0 version requires spaCy < 3.3.0 

### ISSUE THREAD

**Issue by Dris101** [KennethEnevoldsen/spacy-wrap#37]
## How to reproduce the behaviour
pyproject.toml contains
```toml
spacy = "^3.3.0"
```

Add spacy-wrap with

```
poetry add spacy_wrap
```

## Info about spaCy

- **spaCy version:** 3.3.0
- **Platform:** Windows-10-10.0.19043-SP0
- **Python version:** 3.9.10
- **Pipelines:** en_core_web_sm (3.3.0), en_core_web_trf (3.3.0)

## Issue
Dependency resolution fails with poetry

```
SolverProblemError

  Because spacy-wrap (1.0.0) depends on spacy (>=3.2.1,<3.3.0)
   and no versions of spacy-wrap match >1.0.0,<2.0.0, spacy-wrap (>=1.0.0,<2.0.0) requires spacy (>=3.2.1,<3.3.0).
  So, because spacytest depends on both spacy (^3.3.0) and spacy-wrap (^1.0.0), version solving failed.
```

setup,cfg still has

```cfg
install_requires = 
	spacy_transformers>=1.1.4,<1.2.0
	spacy>=3.2.1,<3.3.0
	thinc>=8.0.13,<8.1.0
```

**Comment by KennethEnevoldsen** [comment]
Hi @Dris101, it seems like you are using something called `spacytest` which required a spacy version (^3.3.0), which is causing the problem. So I don't believe the problem lies with spacy-wrap. That being said I have added a new pr #38 which should bump the spacy version to also include version 3.3.X. Will merge it when tests have passed
